# Generated by Django 4.2.29 on 2026-03-27 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_lesson_module_question_questionoption_quiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Turma')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='courses.course', verbose_name='Curso')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_turmas', to=settings.AUTH_USER_MODEL, verbose_name='Professor')),
                ('students', models.ManyToManyField(blank=True, related_name='enrolled_turmas', to=settings.AUTH_USER_MODEL, verbose_name='Alunos')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PresenceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('is_open', models.BooleanField(default=False, help_text='Indicates if students can register presence right now.', verbose_name='Chamada Aberta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_sessions', to='courses.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Presence Session',
                'verbose_name_plural': 'Presence Sessions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PresenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrada em')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='courses.presencesession', verbose_name='Sessão de Presença')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_records', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Presence Record',
                'verbose_name_plural': 'Presence Records',
                'ordering': ['-registered_at'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
