# Generated by Django 4.2.29 on 2026-03-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_turma_presencesession_presencerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='course',
        ),
    ]
